### ISSUE TITLE
Incorrectly generated type in openapi specification for enum

### ISSUE THREAD

**Issue by szagi3891** [poem-web/poem#108] opened 2021-12-04 12:38 UTC
## Expected Behavior
There should never be a clash in the names of the generated structures

## Actual Behavior
There is currently a possible collision in the generated structure names.

## Steps to Reproduce the Problem

1. I created a test repository https://github.com/szagi3891/poem-test
2. You have to clone and then run with cargo run
3. A swagger will be available at "http://127.0.0.1:3000/ui2"

## Specifications

- Version: poem = "1.0.34", poem-openapi = "1.0.34"
- Platform: MacOs
- Subsystem: 

This part was incorrectly generated in the specification, source code:
```
#[derive(Object, Debug, PartialEq)]
pub struct B {
    v4: String,
}

...

#[derive(OneOf, Debug, PartialEq)]
#[oai(property_name = "type")]
pub enum MyObj2 {
    A(A),
    B(B),
}

...

    #[oai(path = "/put2", method = "post")]
    async fn index2(&self, obj: Json<MyObj2>) -> Json<MyObj2> {
        obj
    }
```

Ps.
By the way, fantastic library. My compliments on a great job :)

**Comment by sunli829** [comment] 2021-12-05 02:07
Now if a OpenAPI name conflict is detected when creating schema, it will cause panic.

Released in `v1.0.35`

**Comment by szagi3891** [comment] 2021-12-05 06:01
Interesting solution. This can be pretty cool looking in terms of the amount of code that will be generated from the specification.

When will you be publishing this fix ?

**Comment by sunli829** [comment] 2021-12-05 08:10
Released in `v1.0.35` 🙂

**Comment by szagi3891** [comment] 2021-12-05 08:26
I looked at the wrong package on crate.io :D

**Comment by szagi3891** [comment] 2021-12-05 08:33
I upgraded poem-openapi to version "1.0.35"

Now I get such compilation errors:

```
MacBook-Pro-Grzegorz:poem-test grzegorzszeliga$ cargo run 
   Compiling example-openapi-oneof v0.1.0 (/Users/grzegorzszeliga/Desktop/notatki_main/poem-test)
error[E0282]: type annotations needed
 --> src/my_obj2.rs:3:10
  |
3 | #[derive(Object, Debug, PartialEq)]
  |          ^^^^^^ cannot infer type for type parameter `T` declared on the associated function `create_schema`
  |
  = note: this error originates in the derive macro `Object` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0282]: type annotations needed
 --> src/my_obj2.rs:9:10
  |
9 | #[derive(Object, Debug, PartialEq)]
  |          ^^^^^^ cannot infer type for type parameter `T` declared on the associated function `create_schema`
  |
  = note: this error originates in the derive macro `Object` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0282]: type annotations needed
  --> src/main.rs:11:10
   |
11 | #[derive(Object, Debug, PartialEq)]
   |          ^^^^^^ cannot infer type for type parameter `T` declared on the associated function `create_schema`
   |
   = note: this error originates in the derive macro `Object` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0282]: type annotations needed
  --> src/main.rs:17:10
   |
17 | #[derive(Object, Debug, PartialEq)]
   |          ^^^^^^ cannot infer type for type parameter `T` declared on the associated function `create_schema`
   |
   = note: this error originates in the derive macro `Object` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0282]: type annotations needed
  --> src/main.rs:30:10
   |
30 | #[derive(Object, Debug, PartialEq)]
   |          ^^^^^^ cannot infer type for type parameter `T` declared on the associated function `create_schema`
   |
   = note: this error originates in the derive macro `Object` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0282`.
```

**Comment by sunli829** [comment] 2021-12-05 09:34
It should be caused by the incorrect version of `poem-openapi-derive`, you can use `cargo update` to solve it.

**Comment by szagi3891** [comment] 2021-12-05 09:40
Indeed. Thanks a lot :)

**Closed** 2021-12-05 09:42 UTC
Labels: bug
